### ISSUE TITLE
Serialization??

### ISSUE THREAD

**Issue by shawel** [mourner/flatbush#10]
Hi @mourner,
Thank you for a great library and all the spatial indexing libraries. It has been great help. Is it possible to serialize & persist the index to be used later? and your other libraries spatial libraries in general? 

If not implemented is it a good Idea worth if I look in to it? 

Thanks

**Comment by mourner** [comment]
The entire index is kept in `index.data` as a typed array. You can recreate the index later (but make sure other parameters like `nodeSize` and `numItems` match):

```js
const index = new Flatbush(numItems, nodeSize, Float64Array, data);

// then you can search it immediately
index.search(...);
```

**Comment by mourner** [comment]
@shawel FYI the new release makes it much easier. Now you can save `index.data` somewhere (it's an ArrayBuffer, which can be saved as a binary file), and later recreate the index with `Flatbush.from(data)`.

**Comment by shawel** [comment]
@mourner Thanks for the heads up man. I appreciate it.
