### ISSUE TITLE
Can it work with rotated rectangles?

### ISSUE THREAD

**Issue by danburzo** [mourner/flatbush#14]
I am finally ready to try out an implementation for rbush-knn :) and I was wondering about another issue: can flatbush made to work with rotated rectangles? I *think* I can write a custom collision function, but is there anything about how the rectangles are indexed (assuming indexing on the bounding box of each rectangle, then collision based on the actual shape) that would make this impossible?

Thank you!

**Comment by mourner** [comment]
The packing algorithm only works with axis-aligned boxes. You could add custom code to store items as rotated rectangles, but all R-tree nodes would still be axis-aligned, so this would make no performance difference vs simply going with axis-aligned and then filtering out additionally after a search result. Given there's not much benefit to handling rotation logic in the library, we avoid the complexity.
