### ISSUE TITLE
Proper way to index points

### ISSUE THREAD

**Issue by rreusser** [mourner/flatbush#19]
This may be a silly question, but is it correct to use degenerate bounding boxes for indexing points? This module seems otherwise spot-on, but if I'm interested in points only, is there a variant of the *bush modules that would be more appropriate?

**Comment by rreusser** [comment]
Never mind (though would still love to know if I'm using things correctly). It works great! I'm using it to select and label projected vertices. Thanks so much for this module!!

![selection](https://user-images.githubusercontent.com/572717/46823156-4f7e1a00-cd42-11e8-858a-4b00858b587d.gif)

**Comment by hydrosquall** [comment]
I just this exact same question- I was adding rectangles with the same value for minX and maxX - it worked, but it seemed like we might be able to go even faster if they were stored as simple points. Thanks for the pointer to `kdbush`!
