### ISSUE TITLE
flatbush on a spherical surface

### ISSUE THREAD

**Issue by kkdd** [mourner/flatbush#20]
Hello,
Would flatbush improve its performance when on a spherical surface by using the following spherical Hilbert curve?

- https://repository.library.noaa.gov/view/noaa/11402
- http://blog.christianperone.com/2015/08/googles-s2-geometry-on-the-sphere-cells-and-hilbert-curve/
- https://www.semanticscholar.org/paper/Partitioning-with-Space-Filling-Curves-on-the-Dennis/1758283bc4861d804861d677c95414edc68d3618

**Comment by mourner** [comment]
My gut feeling is it probably won't be a significant performance win, so I'd prefer keeping the code simple.

**Comment by kkdd** [comment]
I see. Thank you for your thinking about it.
