### ISSUE TITLE
TypedArray vs DataView

### ISSUE THREAD

**Issue by IcculusC** [mourner/flatbush#22]
Is there a performance reason for using `TypedArray`s rather than `DataView` in situations where you're setting bytes in the `ArrayBuffer`?  Such as https://github.com/mourner/flatbush/blob/master/index.js#L79

It seems like you could use one `DataView` to set all of those bytes (or even have one global `DataView` operating on the `ArrayBuffer`), so I was just curious if there's a good reason.

**Comment by mourner** [comment]
Yes, `DataView` performance was abysmal compared to typed arrays up until very recent versions of V8, and even then it's slower. (I wonder how other browsers perform, but I'd guess slower too). See https://v8.dev/blog/dataview

**Comment by IcculusC** [comment]
Neat.  I was just benchmarking the initialization with `DataView` and didn't see a major difference +/-.  Thanks for the insight.
