### ISSUE TITLE
KNN with flatbush?

### ISSUE THREAD

**Issue by danburzo** [mourner/flatbush#3]
Hi there,

Sorry to be jumping on this so soon in the development process, but the performance improvements over `rbush` make this package very exciting 😁 

1. Will it be possible to use rbush-knn with flatbush instead?
2. Is there anything I can do to help?

Thanks for all the great work!

**Comment by mourner** [comment]
Yes, this definitely needs a KNN implementation — it will look slightly different than `rbush-knn` due to a different way the tree is stored, but the algorithm is the same. We could also adapt `geokdbush` for it too.

**Comment by mourner** [comment]
@danburzo I made a sample implementation specifically for geographic kNN (to see how fast it will be compared to [geokdbush](https://github.com/mourner/geokdbush)), but you can take the code and simply replace the `boxDist` call with a simple Euclidean distance to turn into a simple kNN: https://github.com/mourner/geoflatbush/blob/master/index.mjs

**Comment by danburzo** [comment]
@mourner, awesome! I will try it out :)
