### ISSUE TITLE
document what search returns

### ISSUE THREAD

**Issue by andrewharvey** [mourner/flatbush#35]
I think it would be helpful for the documentation to explain when a search is found.

Though my testing, I found that inside, exact match, intersecting, single corner touching, and edge touching are all found, only strictly outside was not. Do you think we should add a diagram to illustrate this or just document as text?

```js
const Flatbush = require('flatbush')

const index = new Flatbush(1)
index.add(0, 0, 10, 10)
index.finish()

// inside
console.log(index.search(1, 1, 9, 9))

// exact match
console.log(index.search(0, 0, 10, 10))

// intersecting
console.log(index.search(5, 5, 15, 15))

// single corner touching
console.log(index.search(10, 10, 20, 20))

// edge touching
console.log(index.search(0, 10, 10, 20))

// outside
console.log(index.search(20, 20, 30, 30))
```

**Comment by mourner** [comment]
All similar libraries work the same way, so I think it would be enough to improve the docs text, e.g.:

```diff
-Returns an array of indices of items in a given bounding box.
+Returns an array of indices of items intersecting or touching a given bounding box.
```

**Comment by andrewharvey** [comment]
Perfect, that clarifies it.
