### ISSUE TITLE
maxDistance units when using wgs84 data 

### ISSUE THREAD

**Issue by DavidHequet** [mourner/flatbush#37]
Hi, i cannot find the maxDistance unit from neighbors method in readme.

what is the value i need to set if i want neighbors in max 100 meters from x,y using wgs84 bboxs?

thank you

**Comment by mourner** [comment]
Stock `flatbush` uses Euclidean distances. For geographical ones (which are great arcs on Earth), I made an additional library: https://github.com/mourner/geoflatbush
