### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module when using remix

### ISSUE THREAD

**Issue by vedantroy** [mourner/flatbush#41]
I am trying to use this package with https://github.com/remix-run/remix, but I'm getting the error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/vedantroy/Desktop/pdf-testing/remix-pdf/node_modules/flatbush/index.js from /home/vedantroy/Desktop/pdf-testing/remix-pdf/build/index.js not supported.
Instead change the require of /home/vedantroy/Desktop/pdf-testing/remix-pdf/node_modules/flatbush/index.js in /home/vedantroy/Desktop/pdf-testing/remix-pdf/build/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/vedantroy/Desktop/pdf-testing/remix-pdf/build/index.js:868:31)
```

From reading this error, it seems like "index.js" is not transpiled (i.e it's an ES module and not UMD), but flatbush.js inside of node_modules is transpiled.

I guess the fix would be to have index.js be UMD format. Although, I assume there's a reason you haven't done this.

**Comment by mourner** [comment]
Yes. As you can see in [v4 release notes](https://github.com/mourner/flatbush/releases/tag/v4.0.0), Flatbush v4 drops support for CommonJS entry point and becomes ESM-only for Node (UMD build remains for browsers). Options to work around this, from best to worst:

- Switch from CommonJS to ESM (it's supported in all maintained Node versions, starting with v12).
- Use dynamic import within a CommonJS file (`const flatbush = (await import('flatbush')).default`).
- Pin Flatbush to v3.

You can read more about this approach [here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
