### ISSUE TITLE
Default add() arguments to zero-width rects?

### ISSUE THREAD

**Issue by mootari** [mourner/flatbush#42]
Flatbush is often used to index points, i.e., zero-width rectangles.

How do you feel about changing the signature of `add` to
```js
add(minX, minY, maxX = minX, maxY = minY)
```
as a minor DX improvement for point indexing, so that repeating the coordinates can be avoided in this case?

**Comment by mootari** [comment]
Related: https://github.com/mourner/flatbush/issues/33

**Comment by mourner** [comment]
Yeah, this makes sense! Let's make sure benchmarks don't show a regression (v8 can be weird sometimes) but if not, let's do it.

**Comment by paddymul** [comment]
I would like this feature too.  I'm working to understand the RTree algorithm, and when the bounding rectangles are necessary for search vs the object stored.  I added the #48 PR as a first step.

**Comment by paddymul** [comment]
Ahh.  I think https://github.com/mourner/kdbush solves this usecase.  @mourner Can you confirm?  Thanks for the great work.
