### ISSUE TITLE
`Flatbush.from` with `Uint8Array` input viewing external `ArrayBuffer`

### ISSUE THREAD

**Issue by kylebarron** [mourner/flatbush#54]
👋 In [kylebarron/geo-index](https://github.com/kylebarron/geo-index) I created a new Rust port of Flatbush and Kdbush. This is different from all previous ports I've seen in that a requirement is maintaining FFI compatibility with your reference JS implementations. This means that the Rust library (or a JS binding to it) can produce an index that Flatbush can read, and vice versa. 

One interesting use case is creating a Rust-based WebAssembly library which is able to pass your Flatbush JS a zero-copy slice that Flatbush JS is able to read from. That is, WebAssembly has its own linear memory space contained in an `ArrayBuffer`, and I'd love to have zero-copy interoperability between a `Uint8Array` view exported by the Wasm module and Flatbush JS. This doesn't work today because Flatbush requires `ArrayBuffer` input, so a copy outside of Wasm's memory is needed.

The question here is: would you be interested in a PR that refactors to store a `Uint8Array` internally instead of an `ArrayBuffer`? I think the only changes would be to ensure the array views (like [here](https://github.com/mourner/flatbush/blob/b6c480fbf3d8cf6611445da114d3bb1f68db16ab/index.js#L96)) are created on the specific slice of the underlying buffer referenced by the `Uint8Array` (taking into account the view's `byteOffset`).

**Comment by mourner** [comment]
That's a pretty cool use case! We should definitely support this in some way. However, I'm not confident that changing internal storage to be `Uint8Array`-based is the best solution — e.g. some existing code that depends on Flatbush may rely on `this.data` being an `ArrayBuffer`. 

Would a simpler alternative of accepting an `offset` argument in `Flatbush.from` work? It would be similar to how Node has `Buffer.from(data, offset, length)` signature. Or maybe we could accept a `Uint8Array` there too and just figure out the offsets to pass further from it.

**Comment by mourner** [comment]
> a Rust-based WebAssembly library which is able to pass your Flatbush JS a zero-copy slice that Flatbush JS is able to read from

BTW, it would be interesting to think about the reverse case — being able to generate a Flatbush index in JS and store it in an arbitrary part of an existing `ArrayBuffer` (such as WASM memory) with zero-copy. Might be tricky in terms of API but should be doable.

**Comment by kylebarron** [comment]
That could work for serialization use cases, though for WASM specifically it's non-trivial because the WASM allocator needs to know that the section of memory was updated.

I've been exploring this for a while with tabular data and vector geospatial data with [Arrow](https://arrow.apache.org/) and [GeoArrow](https://geoarrow.org/). E.g. in 
[arrow-js-ffi](https://github.com/kylebarron/arrow-js-ffi) the code is pretty stable to view or copy structured arrays and tables from Wasm to JS. I got a working prototype of the JS library [_writing_ to Wasm](https://github.com/kylebarron/arrow-js-ffi/pull/45/files#diff-72e92c9f4348763ff9a0b7ed7b994b984e505c9e3a7f6b32f1357b323f386865R18-R35), but that required the Wasm module to export a "malloc" function (a simple `type Malloc = (length: number) => number`). (And Arrow specifically has complexities around function pointers that I never really figured out)

For my own purposes for now, for JS -> Wasm I think it'll be easier for the Wasm module to read from JS than for JS to write to Wasm. I have that working [here](https://github.com/kylebarron/arrow-wasm/blob/38aa646f6bf0ec7fe3eacc0d9e47671ac82de7b5/src/arrow1/arrow_js/data.rs) where I first [define duck typing](https://github.com/kylebarron/arrow-wasm/blob/38aa646f6bf0ec7fe3eacc0d9e47671ac82de7b5/src/arrow1/arrow_js/data.rs#L8-L55) that [matches the attributes of an Arrow JS array](https://arrow.apache.org/docs/js/classes/Arrow_dom.Data.html), and then my Wasm module is able to use JS APIs to access the raw `ArrayBuffer`s and copy into Rust.

I'm working on rust-based [geospatial table abstractions](https://github.com/geoarrow/geoarrow-rs) to bind to Python and JS, so my goal demo in the browser is an efficient Wasm-based spatial join, but where a user is also able to access the raw `Flatbush` buffer describing their data to interface with your library.
